### ISSUE TITLE
Issue on page /pairwise/needleman.html

### ISSUE THREAD

**Issue by Saphcas** [statisticalbiotechnology/bibook#1]
In exercise 3.1 you introduced a gap penalty of -3, should that not give S(i,0) and S(0,j) of 0, -3, -6, -9, -12, -15? Additionally if you have a match value of +2 shouldn't the S(1,1)=2 and not 3?

I believe the match and gap values have switched places if I haven't misunderstood the alignment method.

//Cassandra Wivegg

**Comment by percolator** [comment]
Indeed. Cirrected by now!
