### ISSUE TITLE
Issue on page /msa/progressive.html

### ISSUE THREAD

**Issue by HLomundal** [statisticalbiotechnology/bibook#20]
Chapter 11.1.1

Second sentence: "priciples" instead of "principles". 

Chapter 13.2.3

First paragraph, second sentence: "staes" instead of "states". Same sentence "dont" instead of "don't" or "do not". 

Second paragraph, fourth sentence: "Uneavenly" instead of "Unevenly".

Chapter 14

First paragraph, second sentence: "soi" instead of "so".

**Comment by percolator** [comment]
Thanks! Corrected in [8a27be2](https://github.com/statisticalbiotechnology/bibook/commit/8a27be2cf88944fe73adc75c127f82a27be4664d)
