### ISSUE TITLE
Issue on page /protein/matrix.html

### ISSUE THREAD

**Issue by ellari01** [statisticalbiotechnology/bibook#22]
In 9.3.2 the background frequencies are qi and qj while in the rest of the text they seem to be "p" instead of "q". Is that just different ways of writing them or is it an error?

**Comment by percolator** [comment]
Good point. It is somewhat easier to single them out as background frequencies if I use q so I use that variable name all through the text from there on.  Made in [24940a3](https://github.com/statisticalbiotechnology/bibook/commit/24940a3a77cbcea4af744c632ece272dfbdb7cc3)
