### ISSUE TITLE
Issue on page /msa/progressive.html

### ISSUE THREAD

**Issue by Juliaz7** [statisticalbiotechnology/bibook#24]
11.1.2: Extra space in "alignment ." in sentence "Particularly iterative approaches, such as progressive alignment ."

11.2.1: Spelling error "Lests" in sentence Lests assume you start with..."

//Julia Nyman

**Comment by percolator** [comment]
Thanks!

Fixed in f005f5f154d8e3836abe724947489cd696d9df63
