### ISSUE TITLE
Issue on page /pairwise/nw_code.html

### ISSUE THREAD

**Issue by SofieYS** [statisticalbiotechnology/bibook#3]
There are a few minor spelling mistakes in the book. The misspelled words are highlighted in bold. 

In Chapter 3
3.4. Process: 
"Here we use the recursion**,**" - I believe the comma should be a period. 

In Chapter 4
4.2. Global alignments by Needleman-Wunsch:
"Here we **_als_** initiate pointers in the form of a trace matrix." 
"**_Ahgain_** we keep track of the move that lead to a certain position by filling in the trace matrix." 

In Chapter 6
6.2. Local alignments using Smith-Waterman:
"We will implement these difference by **_redifining_** some functions."

In Chapter 7
7.2. Principle:
"Here we cross breed the Needleman-Wunch and the Smith-Waterman **_algoritm_**," 

//Sofie Yu Schmersel

**Comment by percolator** [comment]
Thanks a bunch. I updated the book accordingly.
