### ISSUE TITLE
Issue on page /pairwise/needleman.html

### ISSUE THREAD

**Issue by lpi625** [statisticalbiotechnology/bibook#5]
Both of the tasks in 3.6.3 confuse me. I think there might be a mistake. The rules for both exercises are:

Match: +2
Mismatch: -1
Gap penalty: -3

As far as I understand that means every time one chooses to move vertically or horizontally that leads to a score reduction of  3 and a diagonal movement leads to a score increase of 2, if a match is created. If a mismatch is created, the score is instead reduced by 1. 

In the matrix shown in the answer, the score is only reduced by 2, if the movement is vertical or horizontal and the score is increased by 3, if a diagonal movement is made and a match is created. 

Therefore I would think the rules are supposed to be:

Match: +3
Mismatch: -1
Gap penalty: -2

Or I got something very wrong.

Best regards
Lennart Pielström

**Comment by percolator** [comment]
Indeed. I just updated the exercises.
Thanks!
--Lukas
