### ISSUE TITLE
Issue on page /pairwise/alignment_intro.html

### ISSUE THREAD

**Issue by EmilieTiqaoui** [statisticalbiotechnology/bibook#6]
Hello, 

I think there is 1 mistake at the point "1.2.2 Excercises" (to act in bad faith it begins with the misspelled subtitle "Excercises" instead of "Exercises" :)).

In the exercise 1.1 the sequences are : 
Sequence 1:  GATTACA
Sequence 2: GCATG-C

Knowing that the scoring scheme are:
Match: +1
Mismatch: -1
Gap penalty: -2

As there are 2 matches: G-G, T-T -> +2
                     4 mismatches: A-C, T-A, A-G, A-C -> -4
                     1 Gap penalty -> -2

Total alignment score = +1-1-1+1-1-2-1= -4

BUT
_In the course it is written: 
Matches: G-A, A-A, T-T, C-C → 4 matches × +1 = +4      ---> G-A is not a match and there is no A-A or C-C matches here

Mismatches: G-C, T-G → 2 mismatches × -1 = -2

Gaps: - → 1 gap × -2 = -2

Total alignment score = 4 - 2 - 2 = 0_

I am really looking forward to hear about your return on this as I might be wrong.

Thank you for giving us the opportunity to be involved in such a way in the course.

Emilie Tiqaoui

**Comment by percolator** [comment]
Yes, you are entirely correct. I rehauled the whole ex(c)ercise.
