### ISSUE TITLE
Issue on page /pairwise/alignment_intro.html

### ISSUE THREAD

**Issue by EmilieTiqaoui** [statisticalbiotechnology/bibook#7]
Hello, me again, 

There is maybe a typing mistake at the point "1.2.2 Excercises". At the Exercise 1.2, in the reveal answer it is written : 
Sequence 1: GATTACA
Sequence 2: GAT-GCA

Matches: G-G, A-A, T-T, C-C, A-A → 5 matches × +1 = +5

Mismatches: T-G → 1 mismatch × -1 = -1

Gaps: - → 1 gap × -3 = -3

Total alignment score = 5 - 1 - 3 = 1

The mistake is that the mismatch is with A-G and not T-G. 

I am looking forward to reading you if this is simply an error or a misunderstanding on my side.

Emilie Tiqaoui

**Comment by percolator** [comment]
You are so right!
